[package]
name = "netsec-events"
version.workspace = true
edition.workspace = true

[dependencies]
netsec-models = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
